### ISSUE TITLE
Docs for ApolloX

### ISSUE THREAD

**Issue by happyJ2024** [web3go-xyz/web3go-network-data-collection-agent#2]
ApolloX:
官方文档主要集中在两个地方：

公告/博客/公关稿/产品教学（多语言）：https://apollox.zendesk.com/hc/en-us
白皮书（英语）：https://apollox-finance.gitbook.io/apollox-finance/

**Comment by zhangqixin9527** [comment]
- [x] Finished the code and got the data of ApolloX Finance
- [x] Tried to crawl ApolloX Zendesk
- [x] Merged all docs for ApolloX Finance

[ApolloX Finance Result](https://github.com/web3go-xyz/web3go-network-data-collection-agent/tree/master/ApolloX-Doc/ApolloX_Finance/result)
[ApolloX Finance Merged all docs](https://github.com/web3go-xyz/web3go-network-data-collection-agent/tree/master/ApolloX-Doc/ApolloX_Finance/full_docs_merged)

**Comment by zhangqixin9527** [comment]
Accessing this website requires sending requests using the HTTP/2.0 protocol, and it also has Cloudflare detection. Currently, many Python crawler libraries, such as the Request library, do not have good support for HTTP/2.0. Even when using Java's HTTP client to simulate requests, the correct results may not be returned. However, Chrome, Safari browsers, and even Postman can successfully make requests.

I currently have two ideas: the first one is to study the HTTP/2.0 protocol for requests, and the second one is to use ChromeDriver to simulate browser requests and retrieve the data.

![Image](https://github.com/web3go-xyz/web3go-network-data-collection-agent/assets/24785815/d7c1301d-1501-4207-9e65-e6b9d2cf99a5)


![Image](https://github.com/web3go-xyz/web3go-network-data-collection-agent/assets/24785815/29083267-d6d8-4906-a07c-1f319b04ed0e)


![Image](https://github.com/web3go-xyz/web3go-network-data-collection-agent/assets/24785815/4fd76fbf-9686-4926-ae56-5db3cbecad33)

**Comment by happyJ2024** [comment]
use some autotest framework to mock as Chrome browser.

**Comment by happyJ2024** [comment]
```

import undetected_chromedriver as uc
import time
browser=uc.Chrome()

url='https://apollox.zendesk.com/hc/zh-cn/articles/14456533500697-ALP%E4%BB%8B%E7%BB%8D'

url='https://apollox.zendesk.com/hc/zh-cn/articles/16595815616665-%E9%93%BE%E4%B8%8A%E4%BA%A4%E6%98%93-V2-'
browser.get(url)
delay=5
time.sleep(delay)
html=browser.page_source
print(html)
f = open(str(time.time())+".txt", "w",encoding='utf-8')
f.write(html)
f.close()
```

**Comment by zhangqixin9527** [comment]
- [x] Coding for ApolloX Zendesk by selenium webdriver chrome
- [ ] Cracking Cloudflare's bot verification. Because even with the use of Selenium to simulate human clicks, there is still a mechanism in place to detect and verify if it is a robot accessing the website.
- [ ] Extracting article content by parsing HTML files



![Image](https://github.com/web3go-xyz/web3go-network-data-collection-agent/assets/24785815/9ef8a77d-b4d6-4b41-97a9-c6356b7822de)
